export const ADD_MOVIE_TO_WATCHELIST = "ADD_MOVIE_TO_WATCHEDLIST";
export const REMOVE_MOVIE_FROM_WATCHELIST = "REMOVE_MOVIE_FROM_WATCHELIST";
export const ADD_MOVIE_TO_WATCHED = "ADD_MOVIE_TO_WATCHED";
export const REMOVE_MOVIE_FROM_WATCHED = "REMOVE_MOVIE_FROM_WATCHED";
export const MOVE_TO_WATCHLIST = "MOVE_TO_WATCHLIST";
